### ISSUE TITLE
Ruby 3.1 `require': cannot load such file -- matrix (LoadError)

### ISSUE THREAD

**Issue by kojix2** [AndyObtiva/perfect-shape#1]
Hi Andy

I got the following error when calling glimmer-dsl-libui from Ruby 3.1

```
/home/kojix2/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/perfect-shape-1.0.4/lib/perfect-shape.rb:26:in 
`require': cannot load such file -- matrix (LoadError)
```

I think this error is caused by the change of matrix from default gem to bundled gem since Ruby 3.1.

https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

> The following default gems are now bundled gems. You need to add the following libraries to Gemfile under the bundler environment.
> * matrix 0.4.2

Please consider adding `matrix` to the dependent Gem for Ruby 3.1.

**Comment by AndyObtiva** [comment]
So, the weird thing is I don't get that error in glimmer-dsl-libui under Ruby 3.1 (see screenshot below)

![Screen Shot 2022-06-03 at 9 27 22 AM](https://user-images.githubusercontent.com/23052/171863546-d52ceb26-007b-467b-8c5d-ff9b3e7f9ca9.png)

However, I did get an error when running `rake` tests for `perfect-shape`, so I fixed it in version 1.0.5 and upgraded glimmer-dsl-libui to use it in version 0.5.12.

Good catch! Thank you for reporting.
